#!/usr/bin/python

from math import ceil, floor
from array import array
from exceptions import Exception
from struct import pack_into
from sys import argv, stderr
from xml.etree.ElementTree import ElementTree
from optparse import OptionParser

import yaml

class ImportError (Exception):
    pass

class EpilogData (object):
    """ A class to generate binary Epilog DAT files from a YAML dict.

    Use primarily read and write to read in a YAML stream and write out a
    stream of bytes."""

    # The Epilog DAT format has a bunch of magic values in it, starting
    # at 0x40 and going for a while. Many of these will be replaced later
    # by parameters, but some are either constants or I couldn't figure
    # out their meaning.
    magic40 = array('c', map(chr, [
        0x01, 0x04, 0x00, 0x05, 0xdc, 0x00, 0x70, 0x0a,
        0x1f, 0x66, 0x00, 0x00, 0x02, 0x00, 0x00, 0x01,
        0x3a, 0x03, 0x3a, 0x03, 0x64, 0x00, 0x01, 0x00,
        0x07, 0x00, 0xb0, 0x04, 0x02, 0x00, 0x01, 0x00,
        0x58, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x65, 0x00, 0x74, 0x00, 0x74, 0x00, 0x65, 0x00,
        0x72, 0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x4d, 0x44, 0x50, 0x45,
        0x00, 0x10, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
        0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x27,
        0x10, 0x27, 0x10, 0x27, 0x00, 0x00, 0x10, 0x27,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        ]))

    # "Main" parameters that are allowed, and are passed as strings/keywords.
    main_cstrs = {
    
            'mode': {
                'vector': 0,
                'raster': 1,
                'combined': 2
                },
            'dpi': {
                75: 75,
                150: 150,
                200: 200,
                300: 300,
                400: 400,
                600: 600,
                1200: 1200
                },
            'optimize': {
                'on': 'on',
                True: 'on',
                'off': 'off',
                False: 'off',
                'inside': 'inside'
                },
            'dither': {
                'standard': 1,
                'floyd': 2,
                'bright': 3,
                'lowres': 4,
                'jarvis': 5,
                'stucki': 6
                }
            }

    # "Main" parameters that are allowed, and passed as numbers in a range.
    main_ranges = {
        'width': [0, 36],
        'height': [0, 24],
        'raster-power': [0, 100],
        'raster-speed': [1, 100],
        'vector-power': [0, 100],
        'vector-speed': [1, 100],
        'frequency': [10, 5000],
        }

    # Color mapping parameters. If provided at all, all parameters and ranges
    # must be provided.
    color_cstrs = {
            'raster': {True: 1, 'on': 1, False: 0, 'off': 0},
            'vector': {True: 1, 'on': 1, False: 0, 'off': 0},
            'air': {True: 1, 'on': 1, False: 0, 'off': 0}
            }
    color_ranges = {
            'power': [0, 100],
            'speed': [1, 100],
            'frequency': [10, 5000],
            'color': [0, 0xFFFFFF]
            }

    # From above, these parameters are required - we can't safely pick defaults.
    reqs = [
            'mode',
            'dpi',
            'height',
            'width',
            'raster-power',
            'raster-speed',
            'vector-power',
            'vector-speed',
            'frequency',
            ]

    # These parameters are safe defaults, so they're optional.
    opts = {
            'optimize': 'on',
            'dither': 'jarvis',
            'colors': {}
            }

    def check_keys(self, cs, rs, reqs, opts, checkme):
        """ Internal function to check a YAML object against a set of required
        and optional settings.

        This doesn't use just the dicts above directly because it's called two
        different ways - once for the main settings, and once per color line 
        if color mapping is used.

        cs: string parameters
        rs: range parameters
        reqs: required parameters
        opts: optional parameters

        checkme: the YAML dict to check."""

        parsed = dict()

        for key in reqs:
            if not checkme.has_key(key):
                raise ImportError(key + " must be specified")

        for key in opts:
            if not checkme.has_key(key):
                checkme[key] = opts[key]

        for key, value in checkme.iteritems():
            if cs.has_key(key):
                if not cs[key].has_key(value):
                    raise ImportError(key + " must take a value of " + repr(cs[key].keys()))
                else:
                    parsed[key] = cs[key][value]

            if rs.has_key(key):
                if  value < rs[key][0] or value > rs[key][1]:
                    raise ImportError(key + " must be between " + repr(rs[key]))
                else:
                    parsed[key] = value

            if not (key in reqs or key in opts.keys()):
                raise ImportError(key + " isn't known to me.")

        return parsed


    def check_colors(self, colors):
        """Internal function to check color mapping lines."""

        parsed_colors = dict()
        if len(colors.keys()) > 16:
            raise ImportError("max 16 colors")

        for key, values in colors.iteritems():
            if not type(key) is int:
                raise ImportError("color key must be integer")
            if not type(values) is dict:
                raise ImportError("color value must be dict")
            parsed_colors[key] = self.check_keys(self.color_cstrs, self.color_ranges,
                    self.color_cstrs.keys() + self.color_ranges.keys(), {}, values)
        
        return parsed_colors

    def check_main(self, main_set):
        """Check a full YAML object with main settings and colors."""

        parsed_colors = {}
        parsed = self.check_keys(self.main_cstrs, self.main_ranges, self.reqs, self.opts, main_set)
        if main_set.has_key('colors'):
            parsed_colors = self.check_colors(main_set['colors'])
            parsed['colors'] = parsed_colors
        return parsed

    def read(self, stream):
        """Read in a stream, convert to YAML, and parse into a valid Epilog
        data set if possible. If not, raise ImportError."""

        inp = yaml.load(stream)
        if not type(inp) is dict:
            ImportError("file not a dictionary")

        self.parsed = self.check_main(inp)
        

    def write(self, stream):
        """Write the data held in this object to an Epilog DAT file."""

        buf = array('c', '\0'*0x0b4c)
        buf[0x40:0x100] = self.magic40

        pack_into("<HH", buf, 0x50, int(ceil(self.parsed['height'] * 254.0)), int(ceil(self.parsed['width'] * 254.0)))
        pack_into("<H", buf, 0x5a, self.parsed['dpi'])
        pack_into("<H", buf, 0x100, self.parsed['raster-power'])
        pack_into("<H", buf, 0x104, self.parsed['raster-speed'])
        pack_into("<H", buf, 0x108, self.parsed['vector-power'])
        pack_into("<H", buf, 0x10c, self.parsed['vector-speed'])
        pack_into("<B", buf, 0x110, self.parsed['mode'])
        pack_into("<H", buf, 0x344, self.parsed['frequency'])
        pack_into("<B", buf, 0x338, 2 if self.parsed['optimize'] in ['on', 'inside'] else 0)
        pack_into("<B", buf, 0xb48, 1 if self.parsed['optimize'] == 'on' else 0)
        pack_into("<B", buf, 0x350, self.parsed['dither'])

        num_colors = len(self.parsed['colors'])
        if num_colors > 0:
            pack_into("<B", buf, 0x318, 1)
            pack_into("<B", buf, 0x320, num_colors)
            offset = 0x560
            for k in sorted(self.parsed['colors'].keys()): 
                c = self.parsed['colors'][k]
                pack_into("<BBBBB", buf, offset, 
                    (c['color'] & 0xFF0000) >> 16,
                    (c['color'] & 0x00FF00) >> 8,
                    (c['color'] & 0x0000FF),
                    c['power'],
                    c['speed'])
                pack_into("<H", buf, offset+8, c['frequency'])
                pack_into("<B", buf, offset+12, c['raster'])
                pack_into("<B", buf, offset+16, c['vector'])
                pack_into("<B", buf, offset+20, c['air'])
                offset += 0x1c

        buf.tofile(stream)


if __name__ == "__main__":
    epilog = EpilogData()
    parser = OptionParser()
    
    parser.add_option("-a", "--auto", dest="autofile",
            help="load size and color map from SVG file", metavar="FILE")

    (options, args) = parser.parse_args()

    try:
        infile = file(args[0], 'r')
        epilog.read(infile)
    except IOError, e:
        print "Error opening file: " + str(e)
        exit(1)
    except ImportError, e:
        print "Error parsing file: " + str(e)
        exit(1)
    
    # SVG automatic loading.
    # We use a color -> color mapping system of
    # Red channel 0-100 => power 0-100
    # Blue channel 0-100 => speed 0-100
    # Green channel 0-250 => freq 0-5000 (*20)

    # Should move this to a separate function/class - we're getting into the
    # SVG parsing business.
    if not options.autofile is None:
        tree = ElementTree(file=options.autofile)
        colors = set()
        bad_strokes = []

        for e in tree.getroot().getiterator():
            try:
                # find nodes with a style and with a non-empty list of bezier points
                if e.get("style") and not e.get("d") == "":

                    #line stroke color is encoded in style parameter with semicolon separated list
                    props = dict(map(lambda s: s.split(':'), e.get("style").split(";")))
                    if props.has_key('stroke') and props['stroke'][0] == '#':

                        # check for strokes that will ruin your job. Ideally this should be a separate
                        # step, but we're here, aren't we?
                        try:
                            opacity = float(props['stroke-opacity'])
                            width = float(props['stroke-width'])
                            if opacity != 1.0 or width >= 0.015 or width == 0.0:
                                if bad_strokes.count((opacity, width)) == 0:
                                    print "Bad strokes found: opacity ", opacity, " width ", width
                                    bad_strokes.append((opacity, width))
                        except:
                            pass
                        colors.add(int(props['stroke'][1:], 16))
            except KeyError:
                pass
            except ValueError:
                pass

        # SVGs are 90pts per inch (in Inkscape).
        w = float(tree.getroot().get("width")) / 90.0
        h = float(tree.getroot().get("height")) / 90.0

        epilog.parsed['width'] = w
        epilog.parsed['height'] = h

        # sort the colors by effective power level, which is power/speed.
        # the big map() is unpacking power, speed, and frequency from the
        # RBG int
        #
        # Played with encoding air in R channel. More trouble than it's worth.
        cparams =sorted(
                filter(lambda (c, p, s, f, a): s > 0,
                    map(lambda c: 
                            ( 
                            c,
                            ((c & 0xFF0000) >> 16), 
                            (c & 0x00FF00) >> 8,
                            (c & 0x0000FF) * 20, 
                            (((c & 0xFF0000) >> 16) / 100) == 1
                            ), 
                        colors)
                    ),
                    lambda (c1, p1, s1, f1, a1), (c2, p2, s2, f2, a2): 
                    cmp(p1 * (1.0/float(s1)), p2 * (1.0/float(s2))))

        # Print out the results 
        i = 1
        for (c, power, speed, freq, air) in cparams:
            print "#", hex(c), "\t", power, "\t", speed, "\t", freq
            epilog.parsed['colors'][i] = dict(color=c, power=power, speed=speed, frequency=freq, air=True, raster=False, vector=True)
            i += 1

    try:
        outfile = file(args[1], 'w')
        epilog.write(outfile)
    except IOError, e:
        print "Error writing file: " + str(e)
        exit(1)
